export enum AirtableTypes {
  attachment = 'multipleAttachments',
  auto_number = 'autoNumber',
  barcode = 'barcode',
  button = 'button',
  checkbox = 'checkbox',
  single_collaborator = 'singleCollaborator',
  count = 'count',
  created_by = 'createdBy',
  created_time = 'createdTime',
  currency = 'currency',
  date = 'date',
  dateTime = 'dateTime',
  duration = 'duration',
  email = 'email',
  formula = 'formula',
  last_modified_by = 'lastModifiedBy',
  last_modified_time = 'lastModifiedTime',
  multiple_record_links = 'multipleRecordLinks',
  multiline_text = 'multilineText',
  lookup = 'lookup',
  multiple_lookup = 'multipleLookupValues',
  multiple_collaborator = 'multipleCollaborators',

  multiple_selects = 'multipleSelects',
  number = 'number',
  percent = 'percent',
  phone_number = 'phoneNumber',
  rating = 'rating',
  rich_text = 'richText',
  rollup = 'rollup',
  single_line_text = 'singleLineText',
  single_select = 'singleSelect',
  external_sync_source = 'externalSyncSource',
  url = 'url',
}
