export enum AirtableTypes {
  attachment = 'multipleAttachments',
  auto_number = 'autoNumber',
  checkbox = 'checkbox',
  single_collaborator = 'singleCollaborator',
  count = 'count',
  created_time = 'createdTime',
  currency = 'currency',
  date = 'date',
  dateTime = 'dateTime',
  duration = 'duration',
  email = 'email',
  formula = 'formula',
  last_modified_time = 'lastModifiedTime',
  multiple_record_links = 'multipleRecordLinks',
  multiline_text = 'multilineText',
  lookup = 'lookup',
  multiple_selects = 'multipleSelects',
  number = 'number',
  phone = 'phone',
  rating = 'rating',
  rich_text = 'richText',
  rollup = 'rollup',
  single_line_text = 'singleLineText',
  single_select = 'singleSelect',
  url = 'url',
}
