import { DataSourceType } from '../enums';

export const DISPLAY_NAME_MAPPER = new Map<DataSourceType, string>([
  [DataSourceType.airtable, 'Airtable'],
  [DataSourceType.postgres, 'Postgres'],
  [DataSourceType.mysql, 'MySQL'],
  [DataSourceType.gsheet, 'Google Sheets'],
  [DataSourceType.snowflake, 'Snowflake'],
  [DataSourceType.vessel, 'Unified Schemas'],
  [DataSourceType.mongodb, 'MongoDB'],
  [DataSourceType.notion, 'Notion'],
  [DataSourceType.salesforce, 'Salesforce'],
  [DataSourceType.hubspot, 'Hubspot'],
  [DataSourceType.zoho, 'Zoho'],
  [DataSourceType.pipedrive, 'Pipedrive'],
  [DataSourceType.dynamic_sales, 'Dynamic Sales'],
  [DataSourceType.dynamodb, 'DynamoDB'],
  [DataSourceType.close, 'Close'],
  [DataSourceType.affinity, 'Affinity'],
  [DataSourceType.sap, 'SAP'],
  [DataSourceType.mondaycom, 'monday.com'],
  [DataSourceType.freshsales, 'Freshsales'],
  [DataSourceType.freshdesk, 'Freshdesk'],
  [DataSourceType.salesloft, 'Salesloft'],
  [DataSourceType.outreach, 'Outreach'],
  [DataSourceType.apollo, 'Apollo'],
  [DataSourceType.active_campaign, 'Active Campaign'],
  [DataSourceType.mailchimp, 'Mailchimp'],
  [DataSourceType.customerio, 'Customer.io'],
  [DataSourceType.slack, 'Slack'],
  [DataSourceType.zendesk, 'Zendesk'],
  [DataSourceType.intercom, 'Intercom'],
  [DataSourceType.front, 'Front'],
  [DataSourceType.woo_commerce, 'WooCommerce'],
  [DataSourceType.shopify, 'Shopify'],
  [DataSourceType.klaviyo, 'Klavio'],
  [DataSourceType.quickbooks, 'Quickbooks'],
  [DataSourceType.xero, 'Xero'],
  [DataSourceType.stripe, 'Stripe'],
  [DataSourceType.click_up, 'ClickUp'],
  [DataSourceType.s3, 'S3'],
  [DataSourceType.braze, 'Braze'],
  [DataSourceType.iterable, 'Iterable'],
  [DataSourceType.google_analytics, 'Google Analytics'],
  [DataSourceType.facebook_ads, 'Facebook Ads'],
  [DataSourceType.jira, 'Jira'],
  [DataSourceType.asana, 'Asana'],
  [DataSourceType.linear, 'Linear'],
  [DataSourceType.netsuite, 'NetSuite'],
  [DataSourceType.marketo, 'Marketo'],
  [DataSourceType.pager_duty, 'PagerDuty'],
  [DataSourceType.twilio, 'Twillio'],
  [DataSourceType.bamboohr, 'BambooHR'],
  [DataSourceType.workday, 'Workday'],
  [DataSourceType.okta, 'Okta'],
  [DataSourceType.podium, 'Podium'],
  [DataSourceType.big_query, 'BigQuery'],
]);
